Attribute VB_Name = "InsertSvgFallback"
Option Explicit

' Insert an SVG as a full-slide visual fallback layer.
' Use this only as a supplement to the editable PPTX generated by scripts.

Sub InsertSvgAsFullSlideFallback()
    Dim svgPath As String
    Dim sld As Slide
    Dim shp As Shape

    svgPath = InputBox("Enter absolute path to reconstruction.svg:", "Insert SVG Fallback")
    If Len(svgPath) = 0 Then Exit Sub

    Set sld = ActivePresentation.Slides(ActiveWindow.View.Slide.SlideIndex)
    Set shp = sld.Shapes.AddPicture(FileName:=svgPath, LinkToFile:=msoFalse, SaveWithDocument:=msoTrue, _
                                   Left:=0, Top:=0, Width:=ActivePresentation.PageSetup.SlideWidth, _
                                   Height:=ActivePresentation.PageSetup.SlideHeight)
    shp.Name = "SVG_Fallback_Reference"
    shp.ZOrder msoSendToBack
End Sub
